### ISSUE TITLE
npm run translate returns an error (Missing translation)

### ISSUE THREAD

**Issue by hilt0n** [voidlabs/versafix-template#29] opened 2022-11-01 20:29 UTC
From a fresh repo clone, I run `npm install` then `npm run translate` and I get the following error:
```
> versafix-template@1.3.2 translate
> node src/translate.js

Missing translation:  options bw=Gray Circle
                |colors=Coloured Circle
                |bwb=Black Circle
                |sqbw=Gray Square
                |sqcolors=Coloured Square
                |sqbwb=Black Square
                |rdcol=Rounded Colors
                |rdbl=Rounded Black
                |rdw=Rounded White
                |sqrdcol=Squared Colors
                |sqrdbl=Squared Black
                |sqrdw=Squared White
                |white=White
                |coloured=Coloured
                |black=Black
Missing translation:  options colors=Coloured Circle
                |bw=Gray Circle
                |bwb=Black Circle
                |sqbw=Gray Square
                |sqcolors=Coloured Square
                |sqbwb=Black Square
                |rdcol=Rounded Colors
                |rdbl=Rounded Black
                |rdw=Rounded White
                |sqrdcol=Squared Colors
                |sqrdbl=Squared Black
                |sqrdw=Squared White
                |white=White
                |coloured=Coloured
                |black=Black
```

My env versions:
```
npm version
{
  'versafix-template': '1.3.2',
  npm: '8.19.2',
  node: '16.18.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

Just as a note, the `npm install` returns the following warnings:
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
```

**Comment by bago** [comment] 2022-11-02 09:51
I cannot reproduce it on my dev branch, but I see it if I download the zip from the release. I guess this is related to different newlines in linux vs windows.

Thank you for reporting!

**Comment by hilt0n** [comment] 2022-11-02 11:19
Thanks to you for the incredible work!

**Comment by bago** [comment] 2022-11-10 13:05
I guess this is fixed in the latest release for each branch.

**Closed by bago** 2022-11-10 13:05 UTC
Labels: bug
